checkpoint_path: 'checkpoints/model_epoch=39-val_dice=0.66.ckpt'

Dataset:
  hip:
    label_color_map:
      Hip: "#FF0000"
    crop_region: [241, 784, 35, 536] # [x1, x2, y1, y2]

  sonance:
    label_color_map:
      Fracture: "#FF0000"
      Metaphysis: "#00FF00"
      Epiphysis: "#0000FF"
      Carpal bone: "#800080"

  shoulder:
    label_color_map:
      Shoulder: "#FF0000"
  
  lung:
    label_color_map:
      Lung: "#FF0000"
      
    

